#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Jul 17 13:39:52 CEST 2022
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto f1f6741dfaaf4609b319d0a0eb616ae0 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot RegisterSyncReset_TestBench_behav xil_defaultlib.RegisterSyncReset_TestBench -log elaborate.log"
xelab -wto f1f6741dfaaf4609b319d0a0eb616ae0 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot RegisterSyncReset_TestBench_behav xil_defaultlib.RegisterSyncReset_TestBench -log elaborate.log

