#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Jul 17 13:39:53 CEST 2022
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim RegisterSyncReset_TestBench_behav -key {Behavioral:sim_1:Functional:RegisterSyncReset_TestBench} -tclbatch RegisterSyncReset_TestBench.tcl -log simulate.log"
xsim RegisterSyncReset_TestBench_behav -key {Behavioral:sim_1:Functional:RegisterSyncReset_TestBench} -tclbatch RegisterSyncReset_TestBench.tcl -log simulate.log

